adding support for compiling as DLL on MSWindows: step 3: added thee necessary preprocessor defines for DLL import/export a la wxWidgets to the various classes.
fix MSVC error C2512: 'wxChartsLabel::wxChartsLabel': no appropriate default constructor available
message : 'wxChartsLabel::wxChartsLabel(void)': function was implicitly deleted because a data member 'wxChartsLabel::m_options' has either no appropriate default constructor or overload resolution was ambiguous

Oddly enough, this fix is only needed when compiling wxCharts as DLL on MSWindows.